### ISSUE TITLE
rime-liangfen 上流

### ISSUE THREAD

**Issue by szc126** [CoelacanthusHex/AUR#2]
建議以沈氏的原品打包。

**Comment by ayaka14732** [comment]
link?

**Comment by szc126** [comment]
就在 readme 裏啊

http://cheonhyeong.com/Simplified/download.html → http://cheonhyeong.com/File/ZHLF_rime_4.0.7z

**Comment by CoelacanthusHex** [comment]
抱歉之前精神状态不好，稍有耽搁，还请见谅

**Comment by ayaka14732** [comment]
@CoelacanthusHex 揉揉妹妹

**Comment by szc126** [comment]
我也是，没问题，又不是那么要紧 <3
